[package]
name = "rust_blockchain"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.39"
colored = "3.0.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.138"
sha2 = "0.10.8"
uuid = { version = "1.4", features = ["v4"] } 
